image: docker:24.0.5

variables:
  COMPOSE_PROJECT_NAME: ci_project_${CI_PIPELINE_ID}
  NGINX_PORT: 8080
  GRAFANA_PORT: 3001
  PROMETHEUS_PORT: 9091

default:
  tags:
    - docker_daemon

stages:
  - build_run_test

build_run_test:
  stage: build_run_test
  when: on_success
  only:
    - main
  before_script:
    - chmod +x tests.sh
  script:
    - sh tests.sh



