services:
  db:
    build: ./app/bdd
    container_name: ${COMPOSE_PROJECT_NAME}_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: counterdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monReseau

  app-flask:
    build: ./app
    container_name: ${COMPOSE_PROJECT_NAME}_app-flask
    restart: always
    networks:
      - monReseau
    depends_on:
      - db

  phpmyadmin:
    build: ./app/phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    networks:
      - monReseau
    depends_on:
      - db

  calculatrice:
    build: ./web
    container_name: ${COMPOSE_PROJECT_NAME}_calculatrice
    networks:
     - monReseau

  tests:
    build: ./ci
    container_name: ${COMPOSE_PROJECT_NAME}_tests
    depends_on:
      - calculatrice
      - app-flask
    networks:
      - monReseau

  nginx:
    build: ./nginx
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - "${NGINX_PORT:-80}:80"
    networks:
      - monReseau
    depends_on:
      - calculatrice
      - app-flask
      - phpmyadmin
      - grafana

  prometheus:
    build: ./monitoring/prometheus
    container_name: ${COMPOSE_PROJECT_NAME}_prometheus
    volumes:
      - prometheus_data:/prometheus
    networks:
      - monReseau
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    depends_on:
      - app-flask
      - calculatrice
    restart: always

  loki:
    build: ./monitoring/loki
    container_name: ${COMPOSE_PROJECT_NAME}_loki
    networks:
      - monReseau
    restart: always

  promtail:
    build: ./monitoring/promtail
    container_name: ${COMPOSE_PROJECT_NAME}_promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monReseau
    depends_on:
      - loki
    restart: always

  grafana:
    build: ./monitoring/grafana
    container_name: ${COMPOSE_PROJECT_NAME}_grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    networks:
      - monReseau
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

volumes:
  mysql_data:
  prometheus_data:
  grafana_data:

networks:
  monReseau:
